### ISSUE TITLE
公開プロキシ関連の修正

### ISSUE THREAD

**Issue by nankachiisai** [zapabob/Python-researchchemcaldrug#2]
まだコードおかしいはずなので、公開プロキシの辺りの手直しをお願いしてもいいですか？

_Originally posted by @zapabob in https://github.com/zapabob/Python-researchchemcaldrug/pull/1#pullrequestreview-1386652775_

**Comment by nankachiisai** [comment]
pull requestのところに書くと、mergeしたあとに見にくくなりますね。
できればバグや今後追加したい機能などはissueとして投稿していただけると助かります。

**Comment by nankachiisai** [comment]
以下に現在のget_adme_data()のコードを示します。

```python
def get_adme_data(smiles):
    # SwissADMEからADMEデータを取得する
    # 1.5分待機する
    time.sleep(90)
    # ランダムにプロキシを選択する
    proxies = [
        {'http':'43.157.66.170:8080'},     # HTTP-HTTPS	Lvl3	Japan country logo Japan	Tokyo		1m
        {'http' :'139.162.78.109:8080'},   # HTTP-HTTPS	Lvl3	Japan country logo Japan	Tokyo		4m
        {'http' :'43.153.222.203:8080'},   #	HTTP-HTTPS	Lvl3
        {'http': '43.138.216.160:8080'},   #        Japan country logo Japan	Tokyo		13m
        {'http':'43.135.182.214:8080'}	   # HTTP-HTTPS	Lvl3 Japan country logo Japan	Tokyo		5h
    ]
    proxy = random.choice(proxies)
    # プロキシを使用してSwissADMEにアクセスする
    r = requests.get('http://www.swissadme.ch/', params={'proxy': proxy, 'SMILES': smiles})
    # 結果を取得した後30s待機する
    adme_data ='SwissADME.csv'
    time.sleep(30)
    return adme_data
```

このコードには問題があります。SwissADMEはページにアクセスして、SMILESを入力して、Runボタンを押さないと結果が出力されないということです。

これに対してはSelenium(以前のバージョンで使っていたかと思いますが)で自動化する必要があります。
手順は下記のとおりです。
1. seleniumで[SwissADME]{http://www.swissadme.ch/index.php)を開く
2. **Enter a list of SMILES here:**のところにSMILESを入力
3. **Run!**ボタンを押す
4. **Retrieve Data:**のCSVのアイコンのリンク先のCSVファイルをダウンロードする
5. ダウンロードしたCSVファイルを*.pyファイルがあるところに置く

面倒なので、少し時間がかかるかもしれません。ChatGPT(GPT-4)をうまく使ってコーディングしたいですね。

**Comment by nankachiisai** [comment]
プロキシ噛ませてSwissADMEにアクセスすると弾かれるみたいです。

**Comment by zapabob** [comment]
学生だとなんか無料でGitHubとIDEがなんか使えるらしいです。
プロクシ無理なら一回のアプリケーション実行ごとにインターバルを設けてGUIボタンにカウントダウン表示を実装したいですね。

**Comment by nankachiisai** [comment]
> 学生だとなんか無料でGitHubとIDEがなんか使えるらしいです。
IDEはあると便利だと思います。
自分はVisual Studio Code使ってますが、これも悪くないです。

> プロクシ無理なら一回のアプリケーション実行ごとにインターバルを設けてGUIボタンにカウントダウン表示を実装したいですね。
PythonでのGUIのツールの作り方がよくわからないので、ちょっくら聞いてみます。

**Comment by nankachiisai** [comment]
さっきのpull requestのコードにプロキシ設定できるようにしていますが、おそらくアクセスできないです。

**Comment by zapabob** [comment]
GUIのバックグラウンドで待機時間を乱数調整しましょう。要するにランダムなアクセスにするんですよ。

**Comment by zapabob** [comment]
60秒を1/6のサイコロで同様に確からしいサイコロを振らせて素数がでたらアクセス再開
